dist: xenial
language: cpp
compiler: 
      -clang

addons:
  apt:
    packages:
    - clang-9
    - libgtest-dev
    - cmake
    - cmake-data 

before_script:
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - export CXX="clang++-9"
  - export CC="clang-9"
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#  - curl -f -T ip_filter_csv-$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER-Linux.deb -udimkush:$BINTRAY_API_KEY "https://api.bintray.com/content/dimkush/filters/ip_filter_csv/$TRAVIS_BUILD_NUMBER/ip_filter_csv-$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"